import { motion, useMotionValue, useReducedMotion, useSpring, useTransform } from "motion/react";
import { useRef, type ButtonHTMLAttributes, type ReactNode } from "react";
import { motionTokens } from "../motion/presets";

export function BlurReveal({ children, className = "" }: { children:string; className?:string }) { const reduced=useReducedMotion(); return <span className={className} aria-label={children}>{children.split("").map((char,index)=><motion.span aria-hidden className="lf-reveal-char" key={`${char}-${index}`} initial={reduced?false:{opacity:0,filter:"blur(8px)",y:7}} animate={{opacity:1,filter:"blur(0px)",y:0}} transition={reduced?{duration:0}:{delay:index*.018,duration:.3}}>{char===" "?"\u00a0":char}</motion.span>)}</span>; }
export function FadeUp({ children, delay=0, className="" }:{children:ReactNode;delay?:number;className?:string}) { const reduced=useReducedMotion(); return <motion.div className={className} initial={reduced?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={reduced?{duration:0}:{duration:.45,delay,ease:motionTokens.easeOut}}>{children}</motion.div>; }
export function TiltCard({children,active=false,onClick,className=""}:{children:ReactNode;active?:boolean;onClick?:()=>void;className?:string}) { const ref=useRef<HTMLButtonElement>(null); const reduced=useReducedMotion(); const x=useMotionValue(0),y=useMotionValue(0); const rotateX=useSpring(useTransform(y,[-.5,.5],[4,-4]),motionTokens.springSoft); const rotateY=useSpring(useTransform(x,[-.5,.5],[-4,4]),motionTokens.springSoft); return <motion.button ref={ref} type="button" className={`lf-tilt ${className}`} data-active={active} style={reduced?undefined:{rotateX,rotateY,transformPerspective:800}} onPointerMove={e=>{if(reduced||!ref.current)return;const r=ref.current.getBoundingClientRect();x.set((e.clientX-r.left)/r.width-.5);y.set((e.clientY-r.top)/r.height-.5)}} onPointerLeave={()=>{x.set(0);y.set(0)}} onClick={onClick} aria-pressed={active}>{children}</motion.button>; }
export function MagneticButton({children,className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>){const ref=useRef<HTMLButtonElement>(null);const reduced=useReducedMotion();const x=useSpring(0,{stiffness:180,damping:18}),y=useSpring(0,{stiffness:180,damping:18});return <motion.button {...props} ref={ref} className={className} style={reduced?undefined:{x,y}} onPointerMove={e=>{if(reduced||!ref.current)return;const r=ref.current.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.13);y.set((e.clientY-r.top-r.height/2)*.13)}} onPointerLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.button>}
export function ColorSelector<T extends string>({items,value,onChange,label="Палитра"}:{items:ReadonlyArray<{id:T;name:string;colors:readonly [string,string]}>;value:T;onChange:(v:T)=>void;label?:string}){return <div className="lf-swatches" role="radiogroup" aria-label={label}>{items.map(i=><motion.button key={i.id} type="button" role="radio" aria-label={i.name} aria-checked={i.id===value} className="lf-swatch" style={{background:`linear-gradient(145deg,${i.colors[0]},${i.colors[1]})`}} whileTap={{scale:.9}} onClick={()=>onChange(i.id)}/>)}</div>}
export function FluidDotOrbit(){const reduced=useReducedMotion();return <span className="lf-fluid-orbit" aria-hidden><i/><motion.b animate={reduced?undefined:{rotate:360}} transition={{duration:1.8,repeat:Infinity,ease:"linear"}}><i/></motion.b></span>}
