#!/usr/bin/env node
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(await readFile(resolve(root, "assets/service-logos/manifest.json"), "utf8"));
const argv = process.argv.slice(2);
const arg = name => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : undefined; };
const target = resolve(arg("--target") || process.cwd());
let choice = arg("--logo");

if (!choice) {
  stdout.write("\nВыберите сервисный логотип:\n\n");
  for (let i = 0; i < manifest.length; i += 5) stdout.write(manifest.slice(i, i + 5).map(x => `${String(x.id).padStart(2,"0")}. ${x.title}`).join("   ") + "\n");
  const rl = createInterface({ input: stdin, output: stdout });
  choice = await rl.question("\nНомер или slug [01]: ") || "01";
  rl.close();
}

const selected = manifest.find(x => String(x.id) === String(Number(choice)) || x.slug === choice || `${String(x.id).padStart(2,"0")}-${x.slug}` === choice);
if (!selected) { console.error(`Неизвестный логотип: ${choice}`); process.exit(1); }
const filename = `${String(selected.id).padStart(2,"0")}-${selected.slug}.svg`;
const publicDir = resolve(target, "public");
const srcDir = resolve(target, "src");
await mkdir(publicDir, { recursive: true }); await mkdir(srcDir, { recursive: true });
await Promise.all([
  copyFile(resolve(root, "assets/service-logos", filename), resolve(publicDir, "brand-logo.svg")),
  copyFile(resolve(root, "assets/service-logos", filename), resolve(publicDir, "favicon.svg")),
  copyFile(resolve(root, "assets/service-logos/loader-marks", filename), resolve(publicDir, "brand-loader-mark.svg"))
]);
const config = `// Generated by @loopframe/design-system — loopframe-brand\nexport const loopframeBrand = ${JSON.stringify({ id:`${String(selected.id).padStart(2,"0")}-${selected.slug}`, title:selected.title, logoSrc:"/brand-logo.svg", loaderSrc:"/brand-loader-mark.svg", tint:selected.palette[0] }, null, 2)} as const;\n`;
await writeFile(resolve(srcDir, "loopframe-brand.ts"), config);
stdout.write(`\n✓ ${selected.title}: brand-logo.svg, favicon.svg, brand-loader-mark.svg\n✓ Конфигурация: ${resolve(srcDir, "loopframe-brand.ts")}\n`);
